import sqlite3
import os
import hashlib
import base64
import logging
import requests

from lxml import etree

from xml_tools import ADEPT_NS, NSMAP, add_subelement, sign_xml
import account
import utils

db_file = 'adl.db'

class Device():
  def __init__(self):
    self.name = None
    self.device_key = None
    self.device_id = None
    self.fingerprint = None
    self.type = 'standalone'

  def __str__(self):
    return "{}: {} ({})".format(self.name, self.type, self.fingerprint)

def get_all_devices(account_urn):
  devices = []

  conn = sqlite3.connect(db_file)
  conn.text_factory = str
  c = conn.cursor()

  rows = c.execute("select device_name, device_key, device_id, fingerprint, device_type from devices where user_id=?", (account_urn,))
  for device in rows.fetchall():
    d = Device()
    d.name, d.device_key, d.device_id, d.fingerprint, d.type = device
    devices.append(d)

  conn.close()

  return devices

def device_list(args, config):
  print("Known devices:")
  default = account.get_default_account()
  devices = get_all_devices(default)
  for d in devices:
    print("-  {} {} - {} ".format(d.name, d.device_id, d.type))
  pass

######### Activation ###########

def build_activation_request(acc, d):
  xml = etree.Element("{%s}activate" % ADEPT_NS, nsmap=NSMAP, attrib = {"requestType": "initial"})
  add_subelement(xml, "fingerprint", d.fingerprint)
  add_subelement(xml, "deviceType", d.type)
  add_subelement(xml, "clientOS", "Windows Vista")
  add_subelement(xml, "clientLocale", "en") # TODO: is it useful to set the real locale ?
  add_subelement(xml, "clientVersion", "ADE WIN 9,0,1131,27")
  add_subelement(xml, "nonce", utils.make_nonce())
  add_subelement(xml, "expiration", utils.get_expiration_date()) 
  add_subelement(xml, "user", acc.urn)

  local_device = acc.get_device('local')
  pk = utils.extract_pk_from_pkcs12(acc, local_device.device_key)
  xml = sign_xml(xml, pk)

  return etree.tostring(xml)

def generate_device_key():
  # Not exactly sure how it is really generated in ADE
  # However as it changes each time, I am guessing it is ok to generate it randomly
  device_key = base64.b64encode(os.urandom(16))
  return device_key

def generate_device_fingerprint():
  # Not sure this is portable
  # Also not the same way it is generated by ADE. Is it an issue ?
  with open('/etc/machine-id', 'r') as f:
    h = hashlib.sha1()
    h.update(f.read())
    d = h.digest()
    return base64.b64encode(d)

def activate(acc, d):
  # Activate this computer
  xml_str = build_activation_request(acc, d)

  svc = "Activate"
  url = "http://adeactivate.adobe.com/adept/"+svc
  try:
    headers = {'content-type': 'application/vnd.adobe.adept+xml'}
    r = requests.post(url, data = xml_str, headers = headers)
    r.raise_for_status()
    device_id = parse_activation_reply(r.text)
  except Exception:
    logging.exception("Could not contact activation server")
    return None

  d.device_id = device_id

  return r.text

def parse_activation_reply(reply):
  tree_root = etree.fromstring(reply)
  device_id = tree_root.find("{http://ns.adobe.com/adept}device").text
  return device_id


def read_device_file(mountpoint):
  try:
    with open("{}/.adobe-digital-editions/device.xml".format(mountpoint), "r") as device_file:
      d = Device()
      tree_root = etree.fromstring(device_file.read())
      d.name = tree_root.find("{http://ns.adobe.com/adept}deviceName").text
      d.type = tree_root.find("{http://ns.adobe.com/adept}deviceType").text
      d.fingerprint = tree_root.find("{http://ns.adobe.com/adept}fingerprint").text

      print("Found device: {}".format(d))
      return d

  except Exception:
    print("Could not find device. Maybe it doesn't support ADEPT DRM ?")
    return None

def read_activation_file(mountpoint):
  try:
    with open("{}/.adobe-digital-editions/activation.xml".format(mountpoint), "r") as activation_file:
      tree_root = etree.fromstring(activation_file.read())
      creds = tree_root.find("{http://ns.adobe.com/adept}credentials")
      username = creds.find("{http://ns.adobe.com/adept}username").text
      plk = creds.find("{http://ns.adobe.com/adept}privateLicenseKey").text

      at = tree_root.find("{http://ns.adobe.com/adept}activationToken")
      device_id = at.find("{http://ns.adobe.com/adept}device").text

      logging.info("This device is already activated for user {}".format(username))
      return username, plk, device_id
  except Exception as e:
    print(e)
    logging.info("Activation file not found")
  return None, None, None

def write_activation_file(mountpoint, content):
  try:
    with open("{}/.adobe-digital-editions/activation.xml".format(mountpoint), "w") as activation_file:
      activation_file.write(content)
  except Exception:
    print("Error while updating device !")
    return False

  return True

def device_register(args, config):
  print("Looking for ADEPT support on {}".format(args.mountpoint))
  d = read_device_file(args.mountpoint)
  if d is None:
    return

  default = account.get_default_account()
  acc     = account.get_account(default)
  
  # Check it is not already in our db
  devices = get_all_devices(default)
  for device in devices:
    if device.fingerprint == d.fingerprint:
      print("Device already exists in the DB")
      return

  # Check if it is not already activated
  username, plk, device_id = read_activation_file(args.mountpoint)
  if username is not None and plk is not None:
    # Already activated
    a = account.find_by_sign(username)
    if a is not None:
      if a.get_private_key() == plk:
        # Activated by a known user
        logging.info("Device is already activated for user {} but is not known by adl, registering it".format(username))
        d.device_id = device_id
        a.devices.append(d)
        a.store()
        return

    logging.error("Device is already activated for an unknown user. Doing nothing or all books on the device will become unreadable")
    return 

  # Activate device
  print("Activating device ...")
  reply = activate(acc, d)
  if reply is None:
    print("Activation failed")
    return

  # Store file in the device
  activation_file_content = build_activation_file(acc, reply, config)
  print(activation_file_content)

  if write_activation_file(args.mountpoint, activation_file_content):
    # Store info in db
    acc.store()
    print("Activation successful")
  else:
    print("Error while writing activation file")

  return

def build_activation_file(acc, reply, config):
  xml = etree.Element("{%s}activationInfo" % ADEPT_NS, nsmap=NSMAP)

  service = etree.Element("{%s}activationServiceInfo" % ADEPT_NS, nsmap=NSMAP)
  xml.append(service)
  add_subelement(service, "authURL", config.auth_url)
  add_subelement(service, "userInfoURL", config.userinfo_url)
  add_subelement(service, "activationURL", config.auth_url)
  add_subelement(service, "certificate", config.activation_certificate)

  cred = etree.Element("{%s}credentials" % ADEPT_NS, nsmap=NSMAP)
  xml.append(cred)
  add_subelement(cred, "user", acc.urn)
  add_subelement(cred, "licenseCertificate", acc.licenseCertificate)
  add_subelement(cred, "privateLicenseKey", acc.get_private_key())
  add_subelement(cred, "authenticationCertificate", config.authentication_certificate)
  user = etree.Element("username", attrib = {"method": acc.sign_method})
  user.text = acc.sign_id
  cred.append(user)

  activationToken = etree.fromstring(reply)
  xml.append(activationToken)

  return etree.tostring(xml)
  
